# Generated by Django 6.1.1 on 2026-10-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=15)),
                ('owner_num', models.IntegerField()),
                ('owner_address', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
